@userId = f643a0d7-6258-4ff0-a8cd-887d221b499e
###
GET http://localhost:8081/api/v1/system/status


###
POST http://localhost:8081/api/v1/user-registration
Content-Type: application/json

{
  "email": "lukaszs@example.com",
  "username": "lukaszkos"
}

###
PUT http://localhost:8081/api/v1/users/{{userId}}
Content-Type: application/json

{
  "email": "updated@example.com"
}


###
GET http://localhost:8081/api/v1/users/{{userId}}


###
POST http://localhost:8081/fake/mail-sender
Content-Type: application/json

{
  "from": "sdf@ge.com",
  "title": "title",
  "to": "sdf@ge.com",
  "content": "sdf@ge.com"
}